mod util;

fn main() -> Result<(), failure::Error> {
    Ok(())
}

